#PYTHON IS A SIMPLE ENGLISH PROGRAMMING LANGUAGE BY WHICH HUMAN CAN TELL THIER COMMANDS,IDEA,ORDER,TASK AND THINGS TO COMPUTER IN A VERY EASY WAY .
#IT IS LIKE BEST FOR BEGINNERS FOR UNDERSTANDING THE CONCEPT .
#YOU WILL BE CURIOUS BY SEEING MY MESSAGE IN GREEN COLOR.THIS ARE CALLED COMMENTS BY WHICH I CAN GIVE INFORMATION TO YOU WITHOUT ACTUALLY TELLING THE COMPUTER
#SO MY MESSAGES WILL BE IN GREEN COLOR